server:
  port: 10086

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lanfilesharingDB?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.ychong.dao
  mapper-locations: classpath:mapper/*.xml